### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#125]
### Component name

_Button_

### Figma link

_[Figma link](https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?type=design&node-id=101%3A16968&t=GVGj9Wfqu0glyKXn-1)_

```[tasklist]
# Design phase
- [ ] Add <component name> Web, iOS & Android variant drafts to Compound Figma documents
- [ ] Create new tokens for <component name>
- [ ] Release <component name> styles
- [ ] Review <component name> web implementation & publish in shared Figma library  
- [ ] Review <component name> mobile implementation & publish in shared Figma library  
- [ ] https://github.com/vector-im/compound/issues/175
```

```[tasklist]
# Development phase
- [x] Implement Button component on Web
- [ ] https://github.com/vector-im/compound/issues/199
- [x] Implement <component name> on iOS
- [ ] https://github.com/vector-im/compound-web/pull/61
```

**Comment by kerryarchibald** [comment]
Based on the demo app this appears to be done on iOS, closing

**Comment by pixlwave** [comment]
@kerryarchibald Unfortunately it is not. We ported the implementation from EX over to Compound in lieu of waiting for @janogarcia to create designs for iOS. It's a good point though, I'll add a section to the sidebar for components which don't have designs to be clear about this.

**Comment by pixlwave** [comment]
Related issue is here: https://github.com/vector-im/compound/issues/208
