### ISSUE TITLE
Sub Nav

### ISSUE THREAD

**Issue by sandhose** [vector-im/compound#201]
### Component name

_Sub Nav_

### Figma link

- Web Figma document link: https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=669%3A2723&mode=design&t=DaagB5lXRDz8rl6f-1
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [ ] Design phase for Web
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] Development phase for Web
- [ ] Development phase for iOS
- [ ] Development phase for Android
```

# Notes

I have a WIP implementation in MAS: https://github.com/matrix-org/matrix-authentication-service/pull/1441
