### ISSUE TITLE
Menu item

### ISSUE THREAD

**Issue by robintown** [vector-im/compound#226]
### Component name

Menu item

### Figma link

- Web Figma document link: https://www.figma.com/file/rTaQE2nIUSLav4Tg3nozq7/Compound-Web-Components?type=design&node-id=712-6909&mode=dev
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [x] Design phase for Web
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] Development phase for Web (@robintown will handle due to Element Call component needs)
- [ ] Development phase for iOS
- [ ] Development phase for Android
```
