### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by robintown** [vector-im/compound#227]
### Component name

Menu

### Figma link

- Web Figma document link: https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?type=design&node-id=39-14979&mode=dev (note: not yet present in the general web components collection! but surely it should be?)
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [ ] Design phase for Web
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] Development phase for Web (@robintown will handle due to Element Call component needs)
- [ ] Development phase for iOS
- [ ] Development phase for Android
```

**Comment by kerryarchibald** [comment]
@janogarcia @pixlwave does the menu concept map to "Action sheet" in iOS?
https://www.figma.com/file/ux3tYoZV9WghC7hHT9Fhk0/Compound-iOS-Components?type=design&node-id=1-2&mode=design&t=i4K1tDtOk1mISyTM-0

**Comment by pixlwave** [comment]
I would have thought semantically it probably maps more directly to the [Context Menu](https://www.figma.com/file/ux3tYoZV9WghC7hHT9Fhk0/Compound-iOS-Components?type=design&node-id=1-3&mode=dev) component, but equally within the app we do seem to use a sheet instead of the context menu for timeline actions and attaching media to the room so I'm not 100% confident on that. What do you think @janogarcia?
