### ISSUE TITLE
Glass effect

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#230]
### Component name

Glass Effect

### Figma link

- Web Figma document link: ...
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [ ] Design phase for Web
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] https://github.com/vector-im/compound-web/pull/97/
- [ ] Development phase for iOS
- [ ] Development phase for Android
```
