### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#231]
### Component name

_ContextMenu_

### Figma link

- Web Figma document link: https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?node-id=39%3A14979&mode=dev ⚠️ to be moved to the EW component library
- iOS Figma document link: ...
- Android Figma document link: ...

```[tasklist]
# Design phase
- [ ] Design phase for Web
- [ ] Move component definition from EC to EW component library
- [ ] Design phase for iOS
- [ ] Design phase for Android
```

```[tasklist]
# Development phase
- [ ] https://github.com/vector-im/compound-web/pull/98
- [ ] Development phase for iOS
- [ ] Development phase for Android
```

**Comment by robintown** [comment]
Is this a duplicate of https://github.com/vector-im/compound/issues/227?
