### ISSUE TITLE
Support multiple icon rendition

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#242]
Mostly content created by @janogarcia , adding here for posterity and continuity

----

We need to use some 48px outline icons, but it looked rather chunky (4px stroke weight) when just linearly scaling the default 24px outline icon (2px stroke weight).

# Experimentation

For large outline icons we'll scale down a 48px icon that is set to 3px stroke weight. That way, the resulting outline icons are optically balanced with the default 24px outline icon.

<img width="844" alt="Screenshot 2023-10-05 at 11 20 07" src="https://github.com/vector-im/compound/assets/769871/5f7fe6d1-9da2-43d7-811a-ce42cf4a29cf">

```[tasklist]
### Tasks
- [ ] Create a template for multiple icon rendition in Figma
- [ ] Define a naming convention for rendition
- [ ] Change the build process for Web (one dynamic SVG?)
- [ ] Change the build process for Android (?)
- [ ] Change the build process for iOS (XCode assets?)
- [ ] Update the release script https://github.com/vector-im/compound-design-tokens/blob/main/docs/icons.md
```
